[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

[[headers]]
  for = "/admin.html"
  [headers.values]
    X-Robots-Tag = "noindex"
